Small text changes and one image update
KapiX/Polyglot pull request #64
Opened 2021-11-03 19:14 UTC by humdingerb

2021-11-03 19:53 UTC, KapiX requested changes
Please remove the URL from commit message as well, I don't think it should be part of the history.

2021-11-03 19:53 UTC, KapiX commented on app/FileTypes/JavaPropertiesFile.php
> -        return 'Java properties';
https://en.wikipedia.org/wiki/.properties is not https://en.wikipedia.org/wiki/Java_(programming_language).

If you insist on changing this, perhaps '.properties (Java)' would work.

2021-11-04 15:41 UTC, humdingerb commented
> If you insist on changing this, perhaps '.properties (Java)' would work.

Not that I insist, but I changed it to '.properties (Java)' anyway. :)

2021-11-04 18:22 UTC, KapiX approved these changes

2021-11-04 18:23 UTC, merged